---
language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.3.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.0"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
    - PUPPET_GEM_VERSION="~> 3.8.0"
    - PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
    - PUPPET_GEM_VERSION="~> 4.0.0"
    - PUPPET_GEM_VERSION="~> 4.1.0"
    - PUPPET_GEM_VERSION="~> 4.2.0"
    - PUPPET_GEM_VERSION="~> 4.3.0"
    - PUPPET_GEM_VERSION="~> 4.4.0"
    - PUPPET_GEM_VERSION="~> 4.5.0"
    - PUPPET_GEM_VERSION="~> 4.6.0"
    - PUPPET_GEM_VERSION="~> 4.7.0"
    - PUPPET_GEM_VERSION="~> 4.8.0"
    - PUPPET_GEM_VERSION="~> 4"
  global:
  - PUBLISHER_LOGIN=saz
  - secure: |-
      KHycFEf0ALVjITczYG0pcfk912muQkbJiGzKa5yyC8C9ppDW+dTYgDQu8AO1KXFHzds
      NUASY2XNjrJNv27w7A2eMp88qU1ID1s8CWALph4fuxGcM/HoPw9q8sldJ9/sHGlY9Ye
      DEeIvgt9qkwKtG/kb7dN7la42nv5fffWE95OU=

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.0.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.1.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.2.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.3.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.4.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.5.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.6.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.7.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.8.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.4.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.5.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.6.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.8.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"

notifications:
  email: false

after_success:
  - 'git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng'
  - '.forge-releng/publish'
